<?php require 'inc/header.php'?>

<h1 class="text-center text-black mt-5 mb-3">Reklamační řád</h1>
<div class="d-flex w-50 mx-auto flex-column text-black flex-wrap">
    <p><strong><u>I. Základní ustanovení</u></strong></p>
    <p>Tyto obchodní podmínky (dále jen „<strong>OP</strong>“) jsou vydané dle zákona č. 89/2012 Sb., občanský zákoník (dále jen „<strong>občanský zákoník</strong>“).<br /> <br /> Název společnosti:<strong> Driedmeats s. r. o.</strong><strong><br /> </strong>IČO:259848442<br /> se sídlem:&nbsp;Václavské náměstí 9 Praha1<br /> zapsané u Městského soudu v Praze, vložka C 316587<br /> kontaktní údaje:&nbsp;<a href="mailto:speedajax13@gmail.com,">speedajax13@gmail.com</a><br /> (dále jen „prodávající“)</p>
    <p>OP platí pro všechny rezervace zboží v rámci služby „Objednat“ (dále jen „služba“ nebo „rezervace“) prostřednictvím stránek <strong>driedmeats.cz</strong>, které provozuje výše uvedená společnost Driedmeats s.r.o., uskutečněné koncovým zákazníkem. Během rezervace má zákazník možnost nahlédnout do těchto obchodních podmínek, vytisknout je a uložit v elektronické podobě. Platné znění těchto OP je na stránkách <a href="/">Driedmeats</a>.</p>
    <p>Použitím služby dochází k návrhu na uzavření kupní smlouvy, k uzavření kupní smlouvy v souladu s těmito OP dojde až při osobním převzetí a uhrazení zboží na místě koupě (Valdštejnská 150/4, Praha 1), a tak nejde o obchod uzavřený distančním způsobem (např. on-line komunikací). Výše uvedené webové stránky provozovatele slouží pouze jako on-line katalog k prezentaci a k rezervaci zboží službou. Převzetí v&nbsp;místě koupě a dopravu zboží si zajišťuje kupující na své náklady.</p>
    <p>Potvrzením objednávky zákazník prohlašuje, že souhlasí s těmito OP platnými k okamžiku použití služby. Po potvrzení objednávky nedochází k uložení OP a ani textu obchodní smlouvy. Kupující však má možnost vytisknout si příslušnou internetovou stránku během použití služby při využití funkce tisku ze svého prohlížeče.</p>
    <p>Osoby, které mají omezenu svéprávnost nebo nenabyly plné svéprávnosti, jsou oprávněny využít nabízeného sortimentu jen v součinnosti se svým zákonným zástupcem či opatrovníkem a s jeho souhlasem.</p>
    <p>&nbsp;</p>
    <p><span style="text-decoration: underline; font-size: 0.875rem;"><strong style="font-family: inherit; font-size: 0.875rem;">II. Ceny a popis</strong></span></p>
    <p>Ceny zboží uvedené na webových stránkách Driedmeats v rámci služby jsou aktuální ceny v českých korunách včetně všech daní a poplatků, platné k okamžiku použití služby a potvrzené prodávajícím. Součástí této služby je také uvedení základní charakteristiky a obrázek zboží na webových stránkách prodávajícího, popis jeho vlastností a další potřebné informace vztahující se k danému zboží.</p>
    <p>Veškerá prezentace zboží umístěná v on-line katalogu obchodu je informativního charakteru a prodávající není povinen uzavřít kupní smlouvu ohledně tohoto zboží. Služba se uskutečňuje výhradně prostřednictvím výše uvedených stránek a její využití není prodávajícím zpoplatněno.</p>
    <p>Kupující bere na vědomí, že ceny zboží na webové stránce se mohou lišit od cen zboží prodávaného jiným, než výše uvedeným způsobem.</p>
    <p>II.1 &nbsp;Kupující používá službu buď prostřednictvím svého zákaznického účtu, pokud provedl předchozí registraci v internetovém on-line katalogu, nebo vyplněním rezervačního formuláře bez registrace.</p>
    <p>II.2 &nbsp;Kupující si vybere zboží, počet kusů zboží a tlačítkem jej vloží do nákupního košíku; dále má možnost zvolit způsob platby na místě koupě. Před odesláním rezervace je kupujícímu umožněno kontrolovat a měnit údaje, které do koše vložil. Údaje uvedené v&nbsp;odeslané rezervaci jsou prodávajícím považovány za správné. Podmínkou platnosti služby je vyplnění všech povinných údajů v objednávkovém formuláři včetně potvrzení kupujícího, že se seznámil s těmito OP.</p>
    <p>II.3 &nbsp;Neprodleně po obdržení rezervace zašle prodávající kupujícímu potvrzení o jejím obdržení na emailovou adresu, kterou kupující při objednávce zadal. Toto potvrzení je automatické a nepovažuje se za uzavření smlouvy. Prodávající bez zbytečného odkladu potvrdí kupujícímu e-mailem či telefonicky termín vyzvednutí.</p>
    <p>II.4 &nbsp;Zboží je zpravidla připraveno k vyzvednutí do 2 pracovních dní od potvrzení objednávky. Termín vyzvednutí zboží je možné po předchozí dohodě s prodávajícím změnit. Nevyzvedne-li kupující zboží v době, kdy je zboží nachystáno k vyzvednutí, služba bude zrušena a prodávající je oprávněn od návrhu kupní smlouvy odstoupit.</p>
    <p>II.5 &nbsp;Platba za zboží v hotovosti či platební kartou proběhne v okamžiku uzavření kupní smlouvy a převzetím zboží. Místem uzavření koupě je adresa Valdštejnská 150/4, 11800 Praha 1. Zboží zůstává do úplného zaplacení a převzetí zboží kupujícím ve vlastnictví prodávajícího. Nebezpečí škody na věci přechází převzetím zboží kupujícím.</p>
    <p>II.6&nbsp; V případě, že některý z požadavků uvedených v rezervaci nemůže prodávající splnit, zašle kupujícímu na jeho emailovou adresu pozměněnou nabídku. Pozměněná nabídka se považuje za nový návrh kupní smlouvy.</p>
    <p><span style="font-family: inherit; font-size: 0.875rem; letter-spacing: 0.1px;">V případě, že došlo ke zjevné chybě na straně prodávajícího při uvedení ceny zboží v on-line katalogu nebo v průběhu rezervace, není prodávající povinen dodat kupujícímu zboží za tuto zcela zjevně chybnou cenu ani v případě, že kupujícímu bylo zasláno automatické potvrzení o obdržení rezervace podle těchto OP. Prodávající informuje kupujícího o chybě bez zbytečného odkladu a zašle kupujícímu na jeho emailovou adresu pozměněnou nabídku. Pozměněná nabídka se považuje za nový návrh kupní smlouvy.</span></p>
    <p>&nbsp;</p>
    <p><span style="text-decoration: underline;"><strong>III. Zákaznický účet</strong></span></p>
    <p>Na základě registrace kupujícího provedené na webové stránce může kupující přistupovat do svého zákaznického účtu. Prostřednictvím svého zákaznického účtu může kupující používat službu. Kupující může službu využít i bez registrace.</p>
    <p>Při registraci do zákaznického účtu a při využívání služby je kupující povinen uvádět správně a pravdivě všechny údaje. Údaje uvedené v uživatelském účtu je kupující při jakékoliv jejich změně povinen aktualizovat. Údaje uvedené kupujícím v zákaznickém účtu a během využití služby jsou prodávajícím považovány za správné.</p>
    <p>Přístup k zákaznickému účtu je zabezpečen uživatelským jménem a heslem. Kupující je povinen zachovávat mlčenlivost ohledně informací nezbytných k přístupu do jeho zákaznického účtu. Prodávající nenese odpovědnost za případné zneužití zákaznického účtu třetími osobami.</p>
    <p>Kupující není oprávněn umožnit využívání zákaznického účtu třetím osobám.</p>
    <p>Prodávající může zrušit uživatelský účet, a to zejména v případě, když kupující svůj uživatelský účet déle nevyužívá, či v případě, kdy kupující poruší své povinnosti z kupní smlouvy a těchto obchodních podmínek.</p>
    <p><span style="font-family: inherit; font-size: 0.875rem; letter-spacing: 0.1px;">Kupující bere na vědomí, že uživatelský účet nemusí být dostupný nepřetržitě, a to zejména s ohledem na nutnou údržbu hardwarového a softwarového vybavení prodávajícího, popř. nutnou údržbu hardwarového a softwarového vybavení třetích osob.</span></p>
    <p>&nbsp;</p>
    <p><span style="text-decoration: underline; font-size: 0.875rem;"><strong style="font-family: inherit; font-size: 0.875rem;">IV. Reklamace</strong></span></p>
    <p>Využití služby není uzavření obchodu distančním způsobem. Práva vznikající z vadného plnění, jakož i práva ze záruky a další podmínky pro uplatňování těchto práv se řídí dle příslušných ustanovení zákona č. 89/2012 Sb., občanského zákoníku.</p>
    <p>IV.1&nbsp; Jako doklad o záruce vystavuje prodejce k zakoupenému zboží doklad o zakoupení se zákonem uvedenými údaji, které jsou zapotřebí pro uplatnění záruky.</p>
    <p>IV.2&nbsp; Lhůta pro uplatnění práv z vadného plnění začíná běžet dnem koupě - převzetí zboží kupujícím, tj. dnem uvedeném na dokladu o zakoupení. Lhůta je 24 měsíců. Pro kupujícího podnikatele může být lhůta pro uplatnění práv z vadného plnění upravena odlišně.</p>
    <p>Lhůta končí dnem, který se číselným označením shoduje se dnem, kdy započala a o příslušný počet měsíců později. Práva z odpovědnosti za vady zboží, pro které platí záruka za jakost, zaniknou, nebyla-li uplatněna v uvedené době.</p>
    <p>V případě vyřízení reklamace formou výměny zboží neběží nová lhůta, rozhodující je lhůta začínající běžet dnem převzetí zboží kupujícím.</p>
    <p>IV.3&nbsp; Prodávající odpovídá kupujícímu, že věc při převzetí nemá vady. Zejména prodávající odpovídá kupujícímu, že v době, kdy kupující věc převzal, má zboží vlastnosti, které si strany ujednaly, a chybí-li ujednání takové vlastnosti, které prodávající popsal v&nbsp;on-line katalogu. Zboží se hodí k účelu, který pro jeho použití prodávající uvádí nebo ke kterému se věc tohoto druhu obvykle používá. Zboží je v odpovídajícím množství, míře nebo hmotnosti a vyhovuje požadavkům právních předpisů.</p>
    <p><span style="font-family: inherit; font-size: 0.875rem; letter-spacing: 0.1px;">Projeví-li se vada v průběhu šesti měsíců od převzetí, má se za to, že věc byla vadná již při převzetí kupujícím, pokud prodejce neprokáže opak. Toto se nevztahuje na zboží, které kupující sám poškodí ať omylem či úmyslně. </span></p>
    <p>&nbsp;</p>
    <p><span style="text-decoration: underline;"><strong>V. Ostatní ujednání</strong></span></p>
    <p>Ostatní situace, zde výslovně neuvedené se řídí dle zákona č. 89/2012 Sb., občanského zákoníku. Veškerá ujednání mezi prodávajícím a kupujícím se řídí právním řádem České republiky. Pokud vztah založený kupní smlouvou obsahuje mezinárodní prvek, pak strany sjednávají, že vztah se řídí právem České republiky.</p>
    <p>Všechna práva k webovým stránkám prodávajícího, zejména autorská práva k obsahu, včetně rozvržení stránky, fotografií, filmů, grafik, ochranných známek, loga a dalšího obsahu a prvků, náleží prodávajícímu. Je zakázáno kopírovat, upravovat nebo jinak používat webové stránky nebo jejich část bez souhlasu prodávajícího.</p>
    <p>Prodávající nenese odpovědnost za chyby vzniklé v důsledku zásahů třetích osob do internetového katalogu a webové stránky nebo v důsledku jeho užití v rozporu s jeho určením. Kupující nesmí při využívání služby používat postupy, které by mohly mít negativní vliv na provoz webové stránky a on-line prezentace zboží a nesmí vykonávat žádnou činnost, která by mohla jemu nebo třetím osobám umožnit neoprávněně zasahovat či neoprávněně užít programové vybavení nebo další součásti tvořící internetový katalog a užívat on-line katalog nebo jeho části či softwarové vybavení takovým způsobem, který by byl v rozporu s jeho určením či účelem.</p>
    <p>Znění OP může prodávající měnit či doplňovat. Tímto ustanovením nejsou dotčena práva a povinnosti vzniklá po dobu účinnosti předchozího znění OP.</p>
    <p>&nbsp;</p>
    <p>Tyto obchodní podmínky nabývají účinnosti dnem 1. 4. 2020.</p>
</div>
<?php require 'inc/footer.php'?>
